config/routes.rb
Rails.application.routes.draw do
  root "flats#index"
  get 'dashboards/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :flats, only: [:new, :show ,:create, :edit, :update, :destroy, :index] do
    resources :bookings
  end
  resources :dashboards, only: [:index]
  # Defines the root path route ("/")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user


  scope :confirmed, -> { where(confirmed: true)}
  scope :unconfirmed, -> { where.not(confirmed: true)}

  validates :guest, :entry_date, presence: true

end

app/models/flat.rb
# class Flat < ApplicationRecord

#   belongs_to :user
#   has_many :bookings, dependent: :destroy

#   # Hello
#   geocoded_by :full_address

#   after_validation :geocode, if: :will_save_change_to_address?
#   validates :title, :price, :guest, :bedroom, :description, :address, :city,  presence: true

#   def full_address
#     [address, city].compact.join(', ')
#   end

#   has_one_attached :photo

# end

class Flat < ApplicationRecord

  include PgSearch::Model

    pg_search_scope :search_by_city,
    against: [:city],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  belongs_to :user
  has_many :bookings, dependent: :destroy

  reverse_geocoded_by :latitude, :longitude

  after_validation :geocode_to_city_level, if: [:will_save_change_to_address?, :will_save_change_to_city?]
  after_validation :reverse_geocode, if: [:will_save_change_to_address?, :will_save_change_to_city?]
  validates :title, :price, :guest, :bedroom, :description, :address,  presence: true


  has_one_attached :photo


  private

  def geocode_to_city_level
    full_address_result = Geocoder.search(address)
    if full_address_result.any?
      full_result = full_address_result.first

      city_name = full_result.city || result.data['place_name']&.split(',')&.first
      if city_name.present?
        city_result = Geocoder.search(city_name)
        if city_result.any?
          city_result = city_result.first
          self.latitude = city_result.latitude
          self.longitude = city_result.longitude
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :flats, dependent: :destroy
  has_many :bookings

  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/bookings_controller.rb
  class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
  end


    def new
      @booking = Booking.new()
    end

    def create
      @flat = Flat.find(params[:flat_id])
      @booking = Booking.new(booking_params)
      @booking.user = current_user
      @booking.flat = @flat # ca ca va bouger aussi

      if @booking.save
        redirect_to dashboards_path
      else
        @bookingatflat = Booking.where(flat: @flat, confirmed: true)
        @tableaudate = @bookingatflat.map do |book|
          {
            from: book.entry_date,
            to: book.out_date
          }
        end
        render "flats/show", locals: {tableaudate: @tableaudate, flat:@flat, booking:@booking} ,status: :unprocessable_entity
      end
    end

    def update
      @booking = Booking.find(params[:id])
      @booking.update(booking_params)
      redirect_to dashboards_path
    end

    def destroy
      @booking = Booking.find(params[:id])
      @booking.destroy
      redirect_to flat_bookings_path, status: :see_other
    end

  def edit
    @booking = Booking.find(params[:id])
  end


    private

    def booking_params
      params.require(:booking).permit(:entry_date, :out_date, :guest, :confirmed)
    end

  end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    @user_bookings = current_user.bookings ## apart ou je vais dormir
    @flats = current_user.flats
    @user_bookings_confirmed = @user_bookings.where(confirmed: true)
    @user_bookings_unconfirmed = @user_bookings.where(confirmed: false)
    @my_flats_bookings_ids = [] ## mes bien booké par dautres users
    @flats.each do |flat|
      @my_flats_bookings_ids << Booking.where(flat: flat).ids
    end

    @my_flats_bookings = Booking.where(id: @my_flats_bookings_ids.flatten)
      # @my_flats_bookings = Booking.joins(:flat).where(flats: { user_id: current_user.id }) ## mes bien booké par dautres users



    @my_flats_bookings_confirmed = @my_flats_bookings.confirmed
    @my_flats_bookings_unconfirmed = @my_flats_bookings.unconfirmed
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all

    if params[:query]
        @flats = Flat.where("city ILIKE ?", "%#{params[:query]}%")
    end

    @city = params[:city]
    @flat = Flat.where(city: @city)
     # The `geocoded` scope filters only flats with coordinates
     @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat})
      }
     end
     # dans flat-controller action-index
      # si params[qurey] => flat.near avec params search et rayon(radius research)

  end

  def new
    @flat = Flat.new
  end

  def show

    @flat = Flat.find(params[:id])
    @booking = Booking.new

    @bookingatflat = Booking.where(flat: @flat, confirmed: true)
    @tableaudate = @bookingatflat.map do |book|
      {
        from: book.entry_date,
        to: book.out_date
      }
    end
    @markers =  [{
        lat: @flat.latitude,
        lng: @flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: @flat})
      }]

      if params[:query].present?
        @flats = @flats.where(city: params[:query])
      end
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to dashboards_path()
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
     @flat = Flat.find(params[:id])
     @flat.user = current_user
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path(@flats), status: :see_other
  end


  private


  def flat_params
    params.require(:flat).permit(:title, :price, :guest, :bedroom, :description, :address, :city, :user, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="show-new-booking-content" data-toggle-target="toggElement">
  <h2>Réservation</h2>

  <div class="new-booking">
    <%= simple_form_for [@flat, @booking] do |f| %>
      <%= f.input :guest, label: "Nombre d'invité(e)s", as: :integer %>
      <p>Choisissez vos dates</p>
        <input type="text" id="date_range" class="form-control" data-controller="datepicker" data-datepicker-dates-value="<%= @tableaudate.to_json %>">
      <%= f.input :entry_date, as: :hidden %>
      <%= f.input :out_date, as: :hidden %>
      <%= f.submit "Valider", class: 'btn btn-primary new-booking-button' %>
    <% end %>
  </div>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/delete.html.erb
<h1>Bookings#delete</h1>
<p>Find me in app/views/bookings/delete.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

<%= form_with model: @booking do |f| %>
  <%= f.label :entry_date %>
  <%= f.text_field :entry_date %>
  <%= f.label :out_date %>
  <%= f.text_field :out_date %>
  <%= f.label :guest %>
  <%= f.text_field :guest %>
  <%= f.submit %>
<% end %>

<p><%= link_to '< Back', bookings_path %></p>

app/views/bookings/show.html.erb
<h1>Detail Booking</h1>

  <p><strong>Date d'arrivée : </strong><%= @booking.entry_date %></p>
  <p><strong>Date de fin : </strong><%= @booking.out_date %></p>
  <p><strong>Nombre de personne : </strong><%= @booking.guest %></p>

  <p><%= link_to '< Back', bookings_path %></p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>

<p>Find me in app/views/bookings/update.html.erb</p>


<%= form_with model: @booking do |f| %>
  <%= f.label :entry_date %>
  <%= f.text_field :entry_date %>
  <%= f.label :out_date %>
  <%= f.text_field :out_date %>
  <%= f.label :guest %>
  <%= f.text_field :guest %>
  <%= f.submit %>
<% end %>

<p><%= link_to '< Back', bookings_path %></p>

app/views/dashboards/index.html.erb
<div class="dashboard-container">
  <div class="dashboard-card">
    <div class="dashboard-profil-pic-container">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: "dashboard-profil-pic" %>
      <% end %>
    </div>
    <div class="dashboard-title">
      Le dashboard
    </div>
    <div class="dashboard-title2">
      de <%= current_user.username %>
    </div>

    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="icon-tab-0" data-bs-toggle="tab" href="#icon-tabpanel-0" role="tab" aria-controls="icon-tabpanel-0" aria-selected="true"><i class="fa-solid fa-plane-up"></i> Mes voyages</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="icon-tab-1" data-bs-toggle="tab" href="#icon-tabpanel-1" role="tab" aria-controls="icon-tabpanel-1" aria-selected="false"><i class="fa-solid fa-suitcase"></i> Mes biens</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="icon-tab-2" data-bs-toggle="tab" href="#icon-tabpanel-2" role="tab" aria-controls="icon-tabpanel-2" aria-selected="false"><i class="fa-solid fa-star"></i> Mes réservations</a>
      </li>
    </ul>

    <div class="tab-content pt-5" id="tab-content">
      <div class="tab-pane active" id="icon-tabpanel-0" role="tabpanel" aria-labelledby="icon-tab-0">
        <div class="dashboard-visit-container">
          <div class="dashboard-visit-title">
            <h2> Vos futures visites</h2>
          </div>
        </div>
        <div class="dashboard-visit-confirmed">
          <p>Réservations validés (<%= @user_bookings_confirmed.count  %>)</p>
          <div class="dashboard-visit-list-container">
            <% @user_bookings_confirmed.each do |book| %>
              <div class="dashboard-flat-card card mb-3" style="max-width: 75vw;">
                <div class="row g-0">
                  <div class="dashboard-flat-card-image col-md-3">
                    <% if book.flat.photo.attached? %>
                      <%= cl_image_tag book.flat.photo.key, class: "img-fluid", alt:"flat.title" %>
                    <% end %>
                  </div>
                  <div class="col-md-7">
                    <div class="card-body">
                      <h5 class="card-title"><strong><%= book.flat.title %></strong></h5>
                      <p class="card-text"><%= book.flat.city %></p>
                      <p class="card-text">
                        <i class="fas fa-user"></i>
                        <%= book.flat.guest %> voyageur(s)
                      </p>
                      <p class="card-text">
                        <i class="fas fa-bed"></i>
                        <%= book.flat.bedroom %> chambre(s)
                      </p>
                    </div>
                  </div>
                  <div class="col-md-2 d-flex flex-column justify-content-between p-3">
                    <h5 class="text-end"><strong><%= book.flat.price %> €</strong></h5>
                    <div class="dashboard-flat-card-button d-flex flex-column justify-content-between gap-3">
                      <%= link_to flat_path(book.flat) do %>
                        voir
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="dashboard-visit-unconfirmed">
          <p>Réservations en attende de validation (<%= @user_bookings_unconfirmed.count  %>)</p>
          <div class="dashboard-visit-list-container">
            <% @user_bookings_unconfirmed.each do |book| %>
              <div class="dashboard-visit-list dashboard-boxshadow">
                <p><%= book.flat.title %></p>
                <p>Le <%= book.entry_date %></p>
                <p>Adresse : <%= book.flat.address %></p>
                <%= link_to flat_path(book.flat) do %>
                  voir
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="tab-pane" id="icon-tabpanel-1" role="tabpanel" aria-labelledby="icon-tab-1">
        <div class="dashboard-new-flat-button">
          <%= link_to "flats/new" do  %>
            Mettre un bien en location
          <% end %>
        </div>
        <div class="dashboard-user-flats-container">
          <div class="dashboard-user-flats-title">
            <h2>Mes biens (<%= @flats.count  %>)</h2>
          </div>
          <div class="dashboard-user-flats-list-container">
            <% @flats.each do |flat| %>
              <div class="dashboard-flat-card card mb-3" style="max-width: 75vw;">
                <div class="row g-0">
                  <div class="dashboard-flat-card-image col-md-3">
                    <% if flat.photo.attached? %>
                      <%= cl_image_tag flat.photo.key, class: "img-fluid", alt:"flat.title" %>
                    <% end %>
                  </div>
                  <div class="col-md-7">
                    <div class="card-body">
                      <h5 class="card-title"><strong><%= flat.title %></strong></h5>
                      <p class="card-text"><%= flat.city %></p>
                      <p class="card-text">
                        <i class="fas fa-user"></i>
                        <%= flat.guest %> voyageur(s)
                      </p>
                      <p class="card-text">
                        <i class="fas fa-bed"></i>
                        <%= flat.bedroom %> chambre(s)
                      </p>
                    </div>
                  </div>
                  <div class="col-md-2 d-flex flex-column justify-content-between p-3">
                    <h5 class="text-end"><strong><%= flat.price %> €</strong></h5>
                    <div class="dashboard-flat-card-button d-flex flex-column justify-content-between gap-3">
                      <%= link_to "Voir", flat_path(flat) %>
                      <%= link_to "Modifier", edit_flat_path(flat) %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="tab-pane" id="icon-tabpanel-2" role="tabpanel" aria-labelledby="icon-tab-2">
        <div class="dashboard-booking-container">
          <div class="dashboard-booking-waiting">
            <div class="dashboard-booking-waiting-title">
              <h2>Bookings en attente (<%= @my_flats_bookings_unconfirmed.count  %>)</h2>
            </div>

            <% if @my_flats_bookings_unconfirmed.any? %>
              <% @my_flats_bookings_unconfirmed.each do |booking| %>
                <div class="dashboard-flat-card card mb-3" style="max-width: 40vw;">
                  <div class="row g-0 flex-nowrap">
                    <div class="dashboard-flat-card-image col-md-3">
                      <% if booking.flat.photo.attached? %>
                        <%= cl_image_tag booking.flat.photo.key, class: "img-fluid", alt:"flat.title" %>
                      <% end %>
                    </div>
                    <div class="col-md-6 ms-1">
                      <p class="card-p">Réservation pour</p>
                      <p class="card-p"><strong><%= booking.flat.title %></strong></p>
                      <p class="card-p">du <strong><%= booking.entry_date %></strong> au <strong><%= booking.out_date %></strong></p>
                      <p class="card-p">pour <strong><%= booking.guest %></strong> invité(s)</p>
                      <p class="card-p">par <strong><%= booking.user.username %></strong></p>
                      <div class="card-body"></div>
                    </div>
                    <div class="col-md-3 d-flex flex-column gap-3 p-3 dashboard-flat-card-button">
                      <%= link_to "Accepter", flat_booking_path(booking.flat, booking, booking: { confirmed: true }),
                          data: { turbo_method: :patch, turbo_confirm: "Confirmer cette réservation." } %>
                      <%= link_to "Refuser", flat_booking_path(booking.flat, booking),
                          data: { turbo_method: :delete, turbo_confirm: "Supprimer cette réservation ?" } %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <p><em>Aucune demande en attente.</em></p>
            <% end %>
          </div>

          <div class="dashboard-booking-waiting">
            <div class="dashboard-booking-waiting-title">
              <h2>Historique (<%= @my_flats_bookings_confirmed.count  %>)</h2>
            </div>

            <% if @my_flats_bookings_confirmed.any? %>
              <% @my_flats_bookings_confirmed.each do |booking| %>
                <div class="dashboard-flat-card card mb-3" style="max-width: 40vw;">
                  <div class="row g-0 flex-nowrap">
                    <div class="dashboard-flat-card-image col-md-3">
                      <% if booking.flat.photo.attached? %>
                        <%= cl_image_tag booking.flat.photo.key, class: "img-fluid", alt:"flat.title" %>
                      <% end %>
                    </div>
                    <div class="col-md-5 ms-1">
                      <p class="card-p">Réservation pour</p>
                      <p class="card-p"><strong><%= booking.flat.title %></strong></p>
                      <p class="card-p">du <strong><%= booking.entry_date %></strong> au <strong><%= booking.out_date %></strong></p>
                      <p class="card-p">pour <strong><%= booking.guest %></strong> invité(s)</p>
                      <p class="card-p">par <strong><%= booking.user.username %></strong></p>
                      <div class="card-body"></div>
                    </div>
                    <div class="col-md-4 d-flex flex-column gap-3 p-3 flex-end dashboard-flat-card-button">
                      <h5 class="text-end"><strong><%= booking.flat.price %> €</strong></h5>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <p><em>Aucun historique à afficher.</em></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/_card.html.erb
<%= link_to flat_path(flat) do %>
<div class="index-card">

  <% if flat.photo.attached? %>
    <div class="index-image">
      <%= cl_image_tag flat.photo.key %>
    </div>
  <% end %>
  <div class="card-content">
      <div class="card-header">
          <div class="location"><%= flat.title %></div>
      </div>
      <div class="title"><%= flat.city %></div>
      <div class="details">
          <div class="detail-item">
              <i class="fas fa-user"></i>
              <span><%= flat.guest %> voyageurs</span>
          </div>
          <div class="detail-item">
              <i class="fas fa-bed"></i>
              <span><%= flat.bedroom %> chambres</span>
          </div>
      </div>
      <div class="description"><%= flat.description %></div>
      <div class="price-section">
          <span class="price"><%= flat.price %>€</span>
          <span class="period">par nuit</span>
      </div>
      <div class="host-info">
          <div class="host-avatar"><%= flat.user.username.first.upcase %></div>
          <span class="host-name">Hébergé par <%= flat.user.username %></span>
      </div>
  </div>
</div>
<%end%>

app/views/flats/_info_window.html.erb
<div>
  <h2><%= flat.title %></h2>
  <p><%=  flat.description %></p>
  <%= link_to 'voir', flat_path(flat) %>
</div>

app/views/flats/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a new flat</h3>
        <%= simple_form_for @flat do |f| %>
         <%= f.input :title, label: "Nom", placeholder: 'Cabane dans les bois..' %>
          <%= f.input :price, label: "Prix par nuit" %>
          <%= f.input :guest, label: "Capacité d'accueil (nombre de personne)" %>
          <%= f.input :bedroom, label: "Nombre de chambres" %>
          <%= f.input :description %>
          <%= f.input :address, label: "Adresse (visible une fois votre bien reservé)" ,placeholder: '36 quai des orfevres', input_html: {data: {address_autocomplete_target: "address"}, class: "d-none" },
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
          %>
          <%= f.input :city, label: "Adresse approximative (visible par tous)", placeholder: 'Nom de votre quartier, ville...' %>
          <%= f.input :photo, as: :file %>

          <%= f.submit "Modifier", class: 'btn btn-primary' %>
          <%= link_to "Supprimer", flat_path(@flat),
                          data: { turbo_method: :delete, turbo_confirm: "Are you sure delete this flat?" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="index-logo">
    <%= image_tag("AirPnp2.jpg", alt: "logo") %>
  </div>
<div class="row justify-content-center index-search-bar">
  <div class="col-sm-8 my-3">
    <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control index-flat-search",
            placeholder: "Ville..."
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary index-flat-serach-button" %>
    <% end %>
  </div>
</div>



<div class="index-map-flat-container">
  <div class="index-map-container"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>


  <div class="index-container">
    <div class="flat-container">
      <%@flats.each do |flat| %>
        <div class="flat-card">
        <%= render "card", flat: flat%>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Ajouter un nouvel appartement</h3>
        <%= simple_form_for @flat do |f| %>
           <%= f.input :title, label: "Nom", placeholder: 'Cabane dans les bois..' %>
          <%= f.input :price, label: "Prix par nuit" %>
          <%= f.input :guest, label: "Capacité d'accueil (nombre de personne)" %>
          <%= f.input :bedroom, label: "Nombre de chambres" %>
          <%= f.input :description %>
          <%= f.input :address, label: "Adresse (visible une fois votre bien reservé)" ,placeholder: '36 quai des orfevres', input_html: {data: {address_autocomplete_target: "address"}, class: "d-none" },
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
          %>
          <%= f.input :city, label: "Adresse approximative (visible par tous)", placeholder: 'Nom de votre quartier, ville...' %>
          <%= f.input :photo, as: :file %>

          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="show-flat-container" data-controller="toggle">
        <div class="show-flat-card" data-toggle-target="flatElement">
            <div class="show-flat-image-container">
              <% if @flat.photo.attached? %>
                <div class="show-image">
                  <%= cl_image_tag @flat.photo.key %>
                </div>
              <% end %>
                <div class="show-flat-price-badge">
                    <%=@flat.price %> <small>€ / nuit</small>
                </div>
            </div>

            <div class="show-flat-content">
                <h1 class="show-flat-title"><%= @flat.title %></h1>
                <div class="show-flat-location"><%= @flat.city %></div>

                <div class="show-flat-specs">
                    <div class="show-flat-spec-item">
                        <span class="show-flat-icon">👥</span>
                        <span><%= @flat.guest %> voyageurs</span>
                    </div>
                    <div class="show-flat-spec-item">
                        <span class="show-flat-icon">🛏️</span>
                        <span><%= @flat.bedroom %> chambres</span>
                    </div>
                </div>

                <div class="show-flat-description">
                  <div class="description"><%= @flat.description %></div>
                </div>

                <!-- Emplacement pour la carte -->

                <div class="show-flat-map-container">
                  <div class="index-map-container" style="width: 100%; center: [2.3522, 48.8566], zoom: 9 "
                    data-controller="map"
                    data-map-markers-value="<%= @markers.to_json %>"
                    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
                  </div>
                </div>

                <div class="show-flat-host-info">

                    <div class="show-flat-host-details">

                      <div class="show-flat-host-avatar"><%= @flat.user.username.first.upcase %></div>
                      <div class="show-flat-host-both-info">

                        <h4>Hébergé par <%= @flat.user.username %></h4>
                        <p>Hôte depuis <%= @flat.user.created_at.year %> • Superhôte</p>
                      </div>
                    </div>
                    <% unless @flat.user == current_user %>
                    <div class="show-flat-button">
                       <button data-action="click->toggle#display">Réserver</button>
                    </div>
                    <% end %>

                </div>

            </div>
            <div class="show-new-booking-content <%= 'd-none' unless @booking.errors.any? %>" data-toggle-target="toggElement">
      <%= render "bookings/form", tableaudate: @tableaudate, booking: @booking, flat: @flat %>
    </div>
        </div>

<%# -------------------------------------------------------------------BOUTON NEW FORM%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirPnp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" type="image/jpeg" href="<%= asset_path 'logo.jpg' %>">
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>